.TH ENCRYPTOR 1 "2025-01-01" "1.0.0" "User Commands"
.SH NAME
encryptor \- advanced file encryption tool
.SH SYNOPSIS
.B encryptor
[\fIOPTION\fR]
.SH DESCRIPTION
Advanced file encryption tool with multiple algorithms.
.SH OPTIONS
.TP
.BR \-h ", " \-\-help
Display help message.
.TP
.BR \-v ", " \-\-version
Display version information.
.SH AUTHOR
Written by mpgamer75.