name: Basic Checks

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Check script syntax
      run: |
        echo "Checking Bash syntax..."
        bash -n install.sh
        bash -n encryptor.sh
        echo "✅ All scripts have valid syntax"